import"./modulepreload-polyfill.js";import{r as j,l as D,j as e,a as K,c as O,s as F,d as X,R as G}from"./queueDB.js";const q=4,J={imagen4:"Imagen 4",nano_banana2:"NB 2",nano_banana_pro:"NB Pro",default:"Veo 3.1 Fast",veo2_fast:"Veo 2 Fast",veo3_quality:"Veo 3.1 Quality",veo2_quality:"Veo 2 Quality",veo3_fast_low:"Veo 3.1 Low"},A=({referenceImages:r})=>{var L;if(!((L=r==null?void 0:r.images)!=null&&L.length))return null;const a=r.images,d=r.mode,x=a.slice(0,q),n=a.length-q,b=d==="frames"?"⌗ Fr":"◈ In",_=d==="frames"?`Frames — ${a.length} image${a.length>1?"s":""}`:`Ingredients — ${a.length} image${a.length>1?"s":""}`,v=a.map(u=>u.name).join(", ");return e.jsxs("div",{className:"flex items-center gap-1 flex-shrink-0",title:`Ref images (${_}): ${v}`,children:[e.jsx("span",{className:`text-[8px] font-bold px-1 py-0.5 rounded leading-none flex-shrink-0 ${d==="frames"?"bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300":"bg-violet-100 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300"}`,children:b}),x.map((u,f)=>e.jsx("div",{className:`w-6 h-6 rounded overflow-hidden flex-shrink-0\r
                        ring-1 ring-slate-300 dark:ring-slate-600\r
                        hover:ring-violet-400 dark:hover:ring-violet-500\r
                        transition-all duration-150 hover:scale-110`,title:u.name,children:e.jsx("img",{src:u.data,alt:u.name,className:"w-full h-full object-cover"})},f)),n>0&&e.jsxs("span",{className:`w-6 h-6 rounded flex-shrink-0 flex items-center justify-center\r
                         text-[8px] font-bold bg-slate-200 dark:bg-slate-700\r
                         text-slate-500 dark:text-slate-400\r
                         ring-1 ring-slate-300 dark:ring-slate-600`,children:["+",n]})]})},Y=({task:r,index:a})=>{const d=r.type==="createvideo",x=d?"border-t-blue-500 border-r-blue-500":"border-t-violet-500 border-r-violet-500",n=d?"border-blue-400 text-blue-600 dark:border-blue-500 dark:text-blue-400":"border-violet-400 text-violet-600 dark:border-violet-500 dark:text-violet-400";return r.status==="processed"?e.jsx("div",{className:`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0\r
                    bg-gradient-to-br from-emerald-400 to-emerald-600\r
                    shadow-md shadow-emerald-500/30`,children:e.jsx("svg",{className:"w-3.5 h-3.5 text-white",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:3,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M5 13l4 4L19 7"})})}):r.status==="error"?e.jsx("div",{className:`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0\r
                    bg-gradient-to-br from-red-400 to-red-600\r
                    shadow-md shadow-red-500/30`,children:e.jsx("svg",{className:"w-3.5 h-3.5 text-white",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:3,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M6 18L18 6M6 6l12 12"})})}):r.status==="current"?e.jsxs("div",{className:"relative w-7 h-7 flex-shrink-0",children:[e.jsx("div",{className:`absolute inset-0 rounded-full animate-spin border-2 border-transparent ${x}`}),e.jsx("div",{className:`absolute inset-0 flex items-center justify-center text-[10px] font-bold ${d?"text-blue-600 dark:text-blue-400":"text-violet-600 dark:text-violet-400"}`,children:a+1})]}):e.jsx("div",{className:`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0
                     border-2 bg-white dark:bg-slate-800 text-[10px] font-bold ${n}`,children:a+1})},Q=({type:r})=>e.jsxs("span",{className:`inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full ${r==="createvideo"?"bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300":"bg-violet-100 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300"}`,children:[r==="createvideo"?e.jsx("svg",{className:"w-2.5 h-2.5",fill:"currentColor",viewBox:"0 0 24 24",children:e.jsx("path",{d:"M15 10l4.553-2.069A1 1 0 0121 8.868v6.264a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"})}):e.jsx("svg",{className:"w-2.5 h-2.5",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2.5,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"})}),r==="createvideo"?"Video":"Image"]}),B=`w-full px-2 py-1.5 text-xs font-medium
  text-slate-700 dark:text-slate-300
  bg-slate-50 dark:bg-slate-700/50
  border border-slate-200 dark:border-slate-600
  hover:border-blue-400 dark:hover:border-blue-500
  rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/20
  focus:border-blue-500 transition-all`,V=`w-full px-3 py-2.5 text-sm
  border-2 border-slate-200 dark:border-slate-600 rounded-xl
  bg-slate-50 dark:bg-slate-700/60
  text-slate-900 dark:text-white
  placeholder-slate-400 dark:placeholder-slate-500
  focus:outline-none focus:ring-2 focus:ring-blue-500/30 focus:border-blue-500
  transition-all`,y=({label:r,value:a,color:d})=>e.jsxs("div",{className:`flex flex-col items-center justify-center px-4 py-2\r
                  bg-white/60 dark:bg-slate-700/40 rounded-xl border\r
                  border-slate-200/60 dark:border-slate-600/40 min-w-[72px]`,children:[e.jsx("span",{className:`text-lg font-extrabold leading-none ${d}`,children:a}),e.jsx("span",{className:"text-[10px] font-medium text-slate-500 dark:text-slate-400 mt-0.5",children:r})]});function Z(){var R,S,H,E;const[r,a]=j.useState([]),[d,x]=j.useState(null),[n,b]=j.useState({}),[_,v]=j.useState(!1),[L,u]=j.useState(null);j.useEffect(()=>{f();const t=s=>{s.action==="queueUpdated"&&f()};return chrome.runtime.onMessage.addListener(t),()=>chrome.runtime.onMessage.removeListener(t)},[]);const f=async()=>{try{const t=await D();a(t||[])}catch(t){console.error("❌ [TaskManager]",t)}},W=async t=>{try{await K(t),await f(),chrome.runtime.sendMessage({action:"queueUpdated"})}catch(s){console.error(s)}},z=async()=>{if(confirm("Are you sure you want to clear all tasks?"))try{await O(),a([]),chrome.runtime.sendMessage({action:"queueUpdated"})}catch(t){console.error(t)}},k=async(t,s)=>{try{const o=r.findIndex(N=>N.id===t);if(o===-1)return;const i=[...r],c=i[o],{prompt:m,count:g,model:l,aspectRatio:C}=s;i[o]={...c,prompt:m!==void 0?m:c.prompt,settings:{...c.settings,...g!==void 0&&{count:g},...l!==void 0&&{model:l},...C!==void 0&&{aspectRatio:C}}},await F(i),a(i),chrome.runtime.sendMessage({action:"queueUpdated"})}catch(o){console.error(o)}},P=t=>{var o,i,c;const s=r.find(m=>m.id===t);s&&(x(t),b({prompt:s.prompt||"",count:((o=s.settings)==null?void 0:o.count)||"1",model:((i=s.settings)==null?void 0:i.model)||"default",aspectRatio:((c=s.settings)==null?void 0:c.aspectRatio)||"landscape"}),v(!0))},U=async()=>{if(d)try{const t=r.findIndex(l=>l.id===d);if(t===-1)return;const s=[...r],o=s[t],{prompt:i,count:c,model:m,aspectRatio:g}=n;s[t]={...o,prompt:i,settings:{...o.settings,count:c,model:m,aspectRatio:g}},await F(s),a(s),v(!1),x(null),chrome.runtime.sendMessage({action:"queueUpdated"})}catch(t){console.error(t)}},h=r.length,M=r.filter(t=>t.status==="processed").length,T=r.filter(t=>t.status==="current").length,$=r.filter(t=>t.status==="pending").length,w=r.filter(t=>t.status==="error").length,I=h>0?Math.round(M/h*100):0,p=r.find(t=>t.id===d);return e.jsxs("div",{className:`min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/40 to-cyan-50/30\r
                    dark:from-slate-950 dark:via-slate-900 dark:to-slate-950`,children:[e.jsx("div",{className:`sticky top-0 z-30\r
                      bg-white/80 dark:bg-slate-900/80 backdrop-blur-xl\r
                      border-b border-slate-200/70 dark:border-slate-700/50\r
                      shadow-sm`,children:e.jsxs("div",{className:"max-w-[1400px] mx-auto px-6 py-3 flex items-center gap-5 flex-wrap",children:[e.jsxs("div",{className:"flex items-center gap-3 flex-shrink-0",children:[e.jsx("div",{className:`p-2 bg-gradient-to-br from-blue-500 to-cyan-500\r
                            rounded-xl shadow-md shadow-blue-500/25`,children:e.jsx("svg",{className:"h-5 w-5 text-white",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"})})}),e.jsxs("div",{children:[e.jsx("h1",{className:"text-base font-bold text-slate-900 dark:text-white leading-none",children:"Task Manager"}),e.jsx("p",{className:"text-[11px] text-slate-500 dark:text-slate-400 mt-0.5",children:"Flow Automator"})]})]}),e.jsxs("div",{className:"flex items-center gap-2 flex-wrap",children:[e.jsx(y,{label:"Total",value:h,color:"text-slate-700 dark:text-slate-200"}),e.jsx(y,{label:"Done",value:M,color:"text-emerald-600 dark:text-emerald-400"}),e.jsx(y,{label:"Running",value:T,color:"text-blue-600 dark:text-blue-400"}),e.jsx(y,{label:"Pending",value:$,color:"text-slate-500 dark:text-slate-400"}),w>0&&e.jsx(y,{label:"Errors",value:w,color:"text-red-600 dark:text-red-400"})]}),e.jsxs("div",{className:"flex-1 min-w-[140px] space-y-1",children:[e.jsx("div",{className:"w-full h-1.5 rounded-full bg-slate-200 dark:bg-slate-700 overflow-hidden",children:e.jsx("div",{className:`h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-400\r
                              transition-all duration-700 ease-out`,style:{width:`${I}%`}})}),e.jsxs("div",{className:"flex justify-between items-center",children:[e.jsxs("span",{className:"text-[10px] font-semibold text-slate-500 dark:text-slate-400",children:[I,"% complete"]}),e.jsxs("span",{className:"text-[10px] text-slate-400 dark:text-slate-500",children:[M,"/",h]})]})]}),e.jsxs("button",{onClick:z,disabled:h===0,className:`flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-sm font-semibold\r
                       bg-red-500 hover:bg-red-600 active:bg-red-700 text-white\r
                       shadow-sm shadow-red-500/25\r
                       disabled:opacity-35 disabled:cursor-not-allowed\r
                       hover:scale-[1.03] active:scale-[0.97]\r
                       transition-all duration-200 flex-shrink-0`,children:[e.jsx("svg",{className:"h-3.5 w-3.5",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"})}),"Clear All"]})]})}),e.jsxs("div",{className:"max-w-[1400px] mx-auto px-6 py-6",children:[h===0&&e.jsxs("div",{className:`flex flex-col items-center justify-center py-24 gap-4\r
                          bg-white/60 dark:bg-slate-800/50 backdrop-blur-xl\r
                          rounded-2xl border border-slate-200/60 dark:border-slate-700/40\r
                          shadow-lg`,children:[e.jsx("div",{className:`w-16 h-16 rounded-2xl bg-slate-100 dark:bg-slate-700\r
                            flex items-center justify-center shadow-inner`,children:e.jsx("svg",{className:"h-8 w-8 text-slate-350 dark:text-slate-500",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:1.5,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"})})}),e.jsxs("div",{className:"text-center",children:[e.jsx("h3",{className:"text-base font-semibold text-slate-900 dark:text-white mb-1",children:"No tasks in queue"}),e.jsx("p",{className:"text-sm text-slate-500 dark:text-slate-400",children:"Add tasks from the sidepanel to get started"})]})]}),h>0&&e.jsxs("div",{className:`bg-white/70 dark:bg-slate-800/60 backdrop-blur-xl\r
                          rounded-2xl border border-slate-200/60 dark:border-slate-700/40\r
                          shadow-lg overflow-hidden`,children:[e.jsx("div",{className:"overflow-x-auto",children:e.jsxs("table",{className:"w-full min-w-[720px] border-collapse table-fixed",children:[e.jsxs("colgroup",{children:[e.jsx("col",{style:{width:"5%"}}),e.jsx("col",{style:{width:"9%"}}),e.jsx("col",{style:{width:"28%"}}),e.jsx("col",{style:{width:"7%"}}),e.jsx("col",{style:{width:"16%"}}),e.jsx("col",{style:{width:"9%"}}),e.jsx("col",{style:{width:"16%"}}),e.jsx("col",{style:{width:"10%"}})]}),e.jsx("thead",{children:e.jsx("tr",{className:`bg-gradient-to-r from-slate-50/80 to-blue-50/40\r
                               dark:from-slate-800/80 dark:to-blue-950/30\r
                               border-b border-slate-200/70 dark:border-slate-700/50`,children:["#","Type","Prompt","Count","Model","Ratio","Preview","Actions"].map((t,s)=>e.jsx("th",{className:`py-2.5 px-3 text-[10px] font-bold uppercase tracking-wider
                                    text-slate-400 dark:text-slate-500
                                    ${s===0||s===7?"text-center":"text-left"}`,children:t},t))})}),e.jsx("tbody",{className:"divide-y divide-slate-100/70 dark:divide-slate-700/40",children:r.map((t,s)=>{var o,i,c,m,g;return e.jsxs("tr",{className:`group transition-colors duration-100
                                  hover:bg-blue-50/30 dark:hover:bg-blue-950/15
                                  ${t.status==="current"?"bg-blue-50/40 dark:bg-blue-950/20":t.status==="processed"?"bg-emerald-50/20 dark:bg-emerald-950/10":t.status==="error"?"bg-red-50/20 dark:bg-red-950/10":""}`,children:[e.jsx("td",{className:"py-2.5 px-3 text-center",children:e.jsx("div",{className:"flex justify-center",children:e.jsx(Y,{task:t,index:s})})}),e.jsx("td",{className:"py-2.5 px-3",children:e.jsx(Q,{type:t.type})}),e.jsx("td",{className:"py-2 px-2 align-top",children:L===t.id?e.jsx("textarea",{autoFocus:!0,value:t.prompt||"",onChange:l=>a(C=>C.map(N=>N.id===t.id?{...N,prompt:l.target.value}:N)),onBlur:l=>{k(t.id,{prompt:l.target.value}),u(null)},onKeyDown:l=>{l.key==="Escape"&&(k(t.id,{prompt:l.target.value}),u(null))},rows:4,className:`w-full px-2.5 py-2 text-sm\r
                            text-slate-800 dark:text-slate-200\r
                            bg-white dark:bg-slate-700/80\r
                            border-2 border-blue-500 dark:border-blue-400\r
                            rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/25\r
                            resize-none shadow-lg shadow-blue-500/10\r
                            transition-all duration-150 placeholder:text-slate-400`,placeholder:"Task prompt…"}):e.jsx("div",{onClick:()=>u(t.id),className:`w-full px-2.5 py-1.5 text-sm\r
                            text-slate-800 dark:text-slate-200\r
                            bg-transparent border border-transparent rounded-lg\r
                            hover:bg-slate-50 dark:hover:bg-slate-700/40\r
                            hover:border-slate-300 dark:hover:border-slate-600\r
                            cursor-text truncate transition-all duration-150\r
                            min-h-[34px] flex items-center`,title:t.prompt||"Click to edit prompt…",children:t.prompt?e.jsx("span",{className:"truncate block",children:t.prompt}):e.jsx("span",{className:"text-slate-400 dark:text-slate-600 italic",children:"Click to edit…"})})}),e.jsx("td",{className:"py-2 px-2",children:e.jsxs("select",{value:((o=t.settings)==null?void 0:o.count)||"1",onChange:l=>k(t.id,{count:l.target.value}),className:B,children:[e.jsx("option",{value:"1",children:"1×"}),e.jsx("option",{value:"2",children:"2×"}),e.jsx("option",{value:"3",children:"3×"}),e.jsx("option",{value:"4",children:"4×"})]})}),e.jsx("td",{className:"py-2 px-2",children:e.jsx("select",{value:((i=t.settings)==null?void 0:i.model)||"default",onChange:l=>k(t.id,{model:l.target.value}),className:B,children:t.type==="createimage"?e.jsxs(e.Fragment,{children:[e.jsx("option",{value:"imagen4",children:"Imagen 4"}),e.jsx("option",{value:"nano_banana2",children:"NB 2"}),e.jsx("option",{value:"nano_banana_pro",children:"NB Pro"})]}):e.jsxs(e.Fragment,{children:[e.jsx("option",{value:"default",children:"Veo 3.1 Fast"}),e.jsx("option",{value:"veo2_fast",children:"Veo 2 Fast"}),e.jsx("option",{value:"veo3_quality",children:"Veo 3.1 Quality"}),e.jsx("option",{value:"veo2_quality",children:"Veo 2 Quality"}),e.jsx("option",{value:"veo3_fast_low",children:"Veo 3.1 Low"})]})})}),e.jsx("td",{className:"py-2 px-2",children:e.jsxs("select",{value:((c=t.settings)==null?void 0:c.aspectRatio)||"landscape",onChange:l=>k(t.id,{aspectRatio:l.target.value}),className:B,children:[e.jsx("option",{value:"landscape",children:"16:9"}),e.jsx("option",{value:"portrait",children:"9:16"})]})}),e.jsx("td",{className:"py-2.5 px-3",children:((g=(m=t.referenceImages)==null?void 0:m.images)==null?void 0:g.length)>0?e.jsx(A,{referenceImages:t.referenceImages}):e.jsx("div",{className:`w-9 h-9 rounded-xl flex items-center justify-center
                                         border ${t.type==="createvideo"?"bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800":"bg-violet-50 dark:bg-violet-900/20 border-violet-200 dark:border-violet-800"}`,children:t.type==="createvideo"?e.jsx("svg",{className:"w-4 h-4 text-blue-400 dark:text-blue-500",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:1.5,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M15 10l4.553-2.069A1 1 0 0121 8.868v6.264a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"})}):e.jsx("svg",{className:"w-4 h-4 text-violet-400 dark:text-violet-500",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:1.5,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"})})})}),e.jsx("td",{className:"py-2.5 px-3",children:e.jsxs("div",{className:"flex items-center justify-center gap-1.5",children:[e.jsx("button",{onClick:()=>P(t.id),className:`h-7 w-7 flex items-center justify-center rounded-lg\r
                                     bg-slate-100 dark:bg-slate-700/50\r
                                     text-slate-400 dark:text-slate-500\r
                                     hover:bg-blue-100 dark:hover:bg-blue-900/30\r
                                     hover:text-blue-600 dark:hover:text-blue-400\r
                                     hover:scale-110 active:scale-95\r
                                     transition-all duration-150`,title:"Edit task",children:e.jsx("svg",{className:"h-3.5 w-3.5",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"})})}),e.jsx("button",{onClick:()=>W(t.id),className:`h-7 w-7 flex items-center justify-center rounded-lg\r
                                     bg-slate-100 dark:bg-slate-700/50\r
                                     text-slate-400 dark:text-slate-500\r
                                     hover:bg-red-100 dark:hover:bg-red-900/30\r
                                     hover:text-red-600 dark:hover:text-red-400\r
                                     hover:scale-110 active:scale-95\r
                                     transition-all duration-150`,title:"Delete task",children:e.jsx("svg",{className:"h-3.5 w-3.5",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"})})})]})})]},t.id)})})]})}),e.jsxs("div",{className:`px-4 py-2.5 bg-slate-50/60 dark:bg-slate-800/40\r
                            border-t border-slate-200/60 dark:border-slate-700/40\r
                            flex items-center justify-between`,children:[e.jsxs("span",{className:"text-[11px] text-slate-400 dark:text-slate-500",children:[h," ",h===1?"task":"tasks"," total"]}),e.jsxs("span",{className:"text-[11px] text-slate-400 dark:text-slate-500",children:[M," completed · ",$," pending · ",T," running",w>0?` · ${w} error${w>1?"s":""}`:""]})]})]})]}),_&&p&&e.jsx("div",{className:`fixed inset-0 z-50 flex items-center justify-center p-4\r
                        bg-black/40 backdrop-blur-sm`,onClick:t=>{t.target===t.currentTarget&&(v(!1),x(null))},children:e.jsxs("div",{className:`bg-white dark:bg-slate-800 rounded-2xl shadow-2xl\r
                          border border-slate-200/50 dark:border-slate-700/40\r
                          w-full max-w-lg overflow-hidden\r
                          animate-in fade-in zoom-in-95 duration-150`,children:[e.jsxs("div",{className:`flex items-center justify-between px-6 py-4\r
                            border-b border-slate-200/60 dark:border-slate-700/40\r
                            bg-gradient-to-r from-blue-50/50 to-cyan-50/30\r
                            dark:from-blue-950/30 dark:to-slate-800/0`,children:[e.jsxs("div",{className:"flex items-center gap-3",children:[e.jsx("div",{className:"p-1.5 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-lg shadow-sm",children:e.jsx("svg",{className:"h-4 w-4 text-white",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"})})}),e.jsxs("div",{children:[e.jsx("h3",{className:"text-sm font-bold text-slate-900 dark:text-white",children:"Edit Task"}),e.jsxs("p",{className:"text-[10px] text-slate-500 dark:text-slate-400",children:[e.jsx(Q,{type:p.type}),e.jsx("span",{className:"ml-1.5",children:J[(R=p.settings)==null?void 0:R.model]||((S=p.settings)==null?void 0:S.model)})]})]})]}),e.jsx("button",{onClick:()=>{v(!1),x(null)},className:`h-7 w-7 flex items-center justify-center rounded-lg\r
                           text-slate-400 hover:text-slate-600 dark:text-slate-500 dark:hover:text-slate-300\r
                           hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors`,children:e.jsx("svg",{className:"h-4 w-4",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M6 18L18 6M6 6l12 12"})})})]}),e.jsxs("div",{className:"px-6 py-5 space-y-5",children:[e.jsxs("div",{children:[e.jsx("label",{className:`block text-xs font-semibold text-slate-500 dark:text-slate-400\r
                                   uppercase tracking-wider mb-2`,children:"Prompt"}),e.jsx("textarea",{value:n.prompt,onChange:t=>b({...n,prompt:t.target.value}),rows:4,className:`${V} resize-none`,placeholder:"Enter task prompt…"})]}),e.jsxs("div",{className:"grid grid-cols-3 gap-3",children:[e.jsxs("div",{children:[e.jsx("label",{className:`block text-xs font-semibold text-slate-500 dark:text-slate-400\r
                                     uppercase tracking-wider mb-2`,children:p.type==="createimage"?"Images":"Videos"}),e.jsxs("select",{value:n.count,onChange:t=>b({...n,count:t.target.value}),className:V,children:[e.jsx("option",{value:"1",children:"1×"}),e.jsx("option",{value:"2",children:"2×"}),e.jsx("option",{value:"3",children:"3×"}),e.jsx("option",{value:"4",children:"4×"})]})]}),e.jsxs("div",{children:[e.jsx("label",{className:`block text-xs font-semibold text-slate-500 dark:text-slate-400\r
                                     uppercase tracking-wider mb-2`,children:"Aspect Ratio"}),e.jsxs("select",{value:n.aspectRatio,onChange:t=>b({...n,aspectRatio:t.target.value}),className:V,children:[e.jsx("option",{value:"landscape",children:"16:9 Landscape"}),e.jsx("option",{value:"portrait",children:"9:16 Portrait"})]})]}),e.jsxs("div",{children:[e.jsx("label",{className:`block text-xs font-semibold text-slate-500 dark:text-slate-400\r
                                     uppercase tracking-wider mb-2`,children:"Model"}),e.jsx("select",{value:n.model,onChange:t=>b({...n,model:t.target.value}),className:V,children:p.type==="createimage"?e.jsxs(e.Fragment,{children:[e.jsx("option",{value:"imagen4",children:"Imagen 4"}),e.jsx("option",{value:"nano_banana2",children:"NB 2"}),e.jsx("option",{value:"nano_banana_pro",children:"NB Pro"})]}):e.jsxs(e.Fragment,{children:[e.jsx("option",{value:"default",children:"Veo 3.1 Fast"}),e.jsx("option",{value:"veo2_fast",children:"Veo 2 Fast"}),e.jsx("option",{value:"veo3_quality",children:"Veo 3.1 Quality"}),e.jsx("option",{value:"veo2_quality",children:"Veo 2 Quality"}),e.jsx("option",{value:"veo3_fast_low",children:"Veo 3.1 Low"})]})})]})]}),((E=(H=p.referenceImages)==null?void 0:H.images)==null?void 0:E.length)>0&&e.jsxs("div",{className:`rounded-xl border border-violet-200/60 dark:border-violet-800/30\r
                                bg-violet-50/40 dark:bg-violet-900/10 p-3.5`,children:[e.jsx("p",{className:`text-[10px] font-bold text-violet-600 dark:text-violet-400\r
                                 uppercase tracking-wider mb-2.5`,children:"Reference Images — read-only"}),e.jsx(A,{referenceImages:p.referenceImages})]})]}),e.jsxs("div",{className:`flex gap-3 px-6 py-4\r
                            border-t border-slate-200/60 dark:border-slate-700/40\r
                            bg-slate-50/50 dark:bg-slate-800/50`,children:[e.jsx("button",{onClick:()=>{v(!1),x(null)},className:`flex-1 px-4 py-2.5 rounded-xl font-semibold text-sm\r
                           bg-white dark:bg-slate-700 border border-slate-200 dark:border-slate-600\r
                           text-slate-700 dark:text-slate-200\r
                           hover:bg-slate-50 dark:hover:bg-slate-600\r
                           transition-colors`,children:"Cancel"}),e.jsx("button",{onClick:U,className:`flex-1 px-4 py-2.5 rounded-xl font-semibold text-sm\r
                           bg-gradient-to-r from-blue-500 to-cyan-500\r
                           hover:from-blue-600 hover:to-cyan-600\r
                           text-white shadow-md shadow-blue-500/20\r
                           hover:shadow-lg hover:scale-[1.02] active:scale-[0.98]\r
                           transition-all duration-200`,children:"Save Changes"})]})]})})]})}X.createRoot(document.getElementById("root")).render(e.jsx(G.StrictMode,{children:e.jsx(Z,{})}));
